# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: blackmythwukong
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: basic-lambda
service: my-ts-service # Name of your service

provider:
  name: aws
  runtime: nodejs18.x # The runtime for your Lambda function
  region: us-east-1 # AWS region where the service will be deployed
  environment:
    NODE_ENV: production # Example environment variable
    ENV_VAR1: "value1"
    ENV_VAR2: "value2"

functions:
  hello:
    handler: src/handler.hello
    memorySize: 512
    timeout: 10 # Timeout setting in seconds
    events:
      - http:
          path: hello
          method: get
          cors: true # Enables CORS for the endpoint

custom:
  serverless-offline:
    port: 4000 # If using serverless-offline for local development
