# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: blackmythwukong
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: basic-lambda
service: my-ts-service # Name of your service

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1 # Adjust this to your preferred region
  environment:
    DYNAMODB_TABLE_NAME: "Test_DynamoDB"

functions:
  fetchItems:
    handler: src/index.handler
    provisionedConcurrency: 2  # Set the desired number of provisioned concurrency instances
    events:
      - http:
          path: items
          method: get
